[package]
name = "numbers_nft"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["json", "blocking"] }
scraper = "0.21.0"
regex = "1.5"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }